# Environments required to execute yarn
#

FROM kkarczmarczyk/node-yarn:6.9
WORKDIR /srv/www

# This directory must be created using root, dunno why
RUN mkdir -p -m 777 /.yarn /.cache /.config

ENTRYPOINT yarn
