export default {
  '/articles/doc/a1': {
    text: 'Content of rumor article a1',
    articleCategories: [
      {
        // Article category generated by AI
        aiModel: 'Some AI model',
        categoryId: 'c1',
        createdAt: '2021-01-01T00:00:00.000Z',
        status: 'NORMAL',
      },
      {
        // Deleted article category
        categoryId: 'c2',
        userId: 'an-user',
        appId: 'WEBSITE',
        status: 'DELETED',
        createdAt: '2021-01-01T00:00:00.000Z',
      },
      {
        // Normal article category
        categoryId: 'c3',
        userId: 'some-user',
        appId: 'WEBSITE',
        status: 'NORMAL',
        createdAt: '2021-01-01T00:00:00.000Z',
      },
    ],
  },
  '/categories/doc/c1': {
    title: 'Category 1',
    description: 'Description for category 1',
  },
  '/categories/doc/c2': {
    title: 'Category 2',
    description: 'Description for category 2',
  },
  '/categories/doc/c3': {
    title: 'Category 3',
    description: 'Description for category 3',
  },
};
