export default {
  '/articles/doc/a1': {
    text: 'No interesting article categories',
    normalArticleCategoryCount: 1,
    articleCategories: [
      {
        // Just one article category generated by AI with no positive votes.
        // Will not be selected.
        aiModel: 'Some AI model',
        categoryId: 'c1',
        createdAt: '2021-01-01T00:00:00.000Z',
        positiveFeedbackCount: 0,
        negativeFeedbackCount: 0,
        status: 'NORMAL',
      },
    ],
  },
  '/articles/doc/a2': {
    text: 'Content of rumor article a2',
    normalArticleCategoryCount: 3,
    articleCategories: [
      {
        // Article category generated by AI, with one positive from non-reviewers
        userId: 'bert',
        appId: 'RUMORS_AI',
        aiModel: 'bert',
        categoryId: 'c1',
        createdAt: '2021-01-01T00:00:00.000Z',
        positiveFeedbackCount: 1,
        negativeFeedbackCount: 0,
        status: 'NORMAL',
      },
      {
        // Deleted article category
        categoryId: 'c2',
        userId: 'an-user',
        appId: 'WEBSITE',
        status: 'DELETED',
        positiveFeedbackCount: 1,
        negativeFeedbackCount: 0,
        createdAt: '2021-01-01T00:00:00.000Z',
      },
      {
        // Old article category by user, no feedbacks
        categoryId: 'c3',
        userId: 'some-user',
        appId: 'WEBSITE',
        status: 'NORMAL',
        positiveFeedbackCount: 0,
        negativeFeedbackCount: 0,
        createdAt: '2020-01-01T00:00:00.000Z',
      },
      {
        // New article category by user, no feedbacks
        categoryId: 'c4',
        userId: 'some-user',
        appId: 'WEBSITE',
        status: 'NORMAL',
        positiveFeedbackCount: 0,
        negativeFeedbackCount: 0,
        createdAt: '2021-01-01T00:00:00.000Z',
      },
    ],
  },
  '/articles/doc/a3': {
    text: 'Content of rumor article a3',
    normalArticleCategoryCount: 2,
    articleCategories: [
      {
        // Old article category generated by AI, with one positive from non-reviewers
        userId: 'bert',
        appId: 'RUMORS_AI',
        aiModel: 'bert',
        categoryId: 'c1',
        createdAt: '2019-01-01T00:00:00.000Z',
        positiveFeedbackCount: 1,
        negativeFeedbackCount: 0,
        status: 'NORMAL',
      },
      {
        // Old article category by user & new negative feedback
        categoryId: 'c2',
        userId: 'an-user',
        appId: 'WEBSITE',
        status: 'NORMAL',
        positiveFeedbackCount: 0,
        negativeFeedbackCount: 1,
        createdAt: '2021-01-01T00:00:00.000Z',
      },
      {
        // New article category generated by AI, with 1 positive feedback from blocked users
        userId: 'bert',
        appId: 'RUMORS_AI',
        aiModel: 'bert',
        categoryId: 'c3',
        createdAt: '2021-01-01T00:00:00.000Z',
        positiveFeedbackCount: 0, // Blocked user upvote does not increment positiveFeedbackCount
        negativeFeedbackCount: 0,
        status: 'NORMAL',
      },
    ],
  },
  '/articlecategoryfeedbacks/doc/a2c1-non-reviewer': {
    articleId: 'a2',
    categoryId: 'c1',
    appId: 'WEBSITE',
    userId: 'non-reviewer',
    score: 1,
    status: 'NORMAL',
    createdAt: '2021-01-01T00:00:00.000Z',
  },
  '/articlecategoryfeedbacks/doc/a2c2-non-reviewer': {
    // Should be irrelevant, since the category is deleted
    articleId: 'a2',
    categoryId: 'c2',
    appId: 'WEBSITE',
    userId: 'non-reviewer',
    score: 1,
    status: 'NORMAL',
    createdAt: '2021-01-01T00:00:00.000Z',
  },
  '/articlecategoryfeedbacks/doc/a3c1-non-reviewer': {
    articleId: 'a3',
    categoryId: 'c1',
    appId: 'WEBSITE',
    userId: 'non-reviewer',
    score: 1,
    status: 'NORMAL',
    createdAt: '2021-01-01T00:00:00.000Z',
  },
  '/articlecategoryfeedbacks/doc/a3c1-reviewer': {
    articleId: 'a3',
    categoryId: 'c1',
    appId: 'RUMORS_AI',
    userId: 'category-reviewer',
    score: -1,
    comment: 'Reviewer comment: a3 is not c1',
    status: 'NORMAL',
    createdAt: '2021-01-01T00:00:00.000Z',
  },
  '/articlecategoryfeedbacks/doc/a3c2-non-reviewer': {
    articleId: 'a3',
    categoryId: 'c2',
    appId: 'WEBSITE',
    userId: 'non-reviewer',
    score: -1,
    status: 'NORMAL',
    createdAt: '2021-01-01T00:00:00.000Z',
  },
  '/articlecategoryfeedbacks/doc/a3c2-reviewer': {
    articleId: 'a3',
    categoryId: 'c2',
    appId: 'RUMORS_AI',
    userId: 'category-reviewer',
    score: 1,
    status: 'NORMAL',
    createdAt: '2021-01-01T00:00:00.000Z',
  },
  '/articlecategoryfeedbacks/doc/a3c3-blocked-user': {
    articleId: 'a3',
    categoryId: 'c3',
    appId: 'WEBSITE',
    userId: 'blocked-user',
    score: 1,
    status: 'BLOCKED',
    createdAt: '2021-01-01T00:00:00.000Z',
  },
  '/categories/doc/c1': {
    title: 'Category 1',
    description: 'Description for category 1',
  },
  '/categories/doc/c2': {
    title: 'Category 2',
    description: 'Description for category 2',
  },
  '/categories/doc/c3': {
    title: 'Category 3',
    description: 'Description for category 3',
  },
  '/categories/doc/c4': {
    title: 'Category 4',
    description: 'Description for category 4',
  },
};
