export default {
  '/articles/doc/a1': {
    text: 'No interesting article categories',
    normalArticleCategoryCount: 1,
    articleCategories: [
      {
        // Just one article category generated by AI with no positive votes.
        // Will not be selected.
        aiModel: 'Some AI model',
        categoryId: 'c1',
        createdAt: '2021-01-01T00:00:00.000Z',
        positiveFeedbackCount: 0,
        negativeFeedbackCount: 0,
        status: 'NORMAL',
      },
    ],
  },
  '/articles/doc/a2': {
    text: 'Content of rumor article a2',
    normalArticleCategoryCount: 2,
    articleCategories: [
      {
        // Article category generated by AI, with one positive from non-reviewers
        aiModel: 'Some AI model',
        categoryId: 'c1',
        createdAt: '2021-01-01T00:00:00.000Z',
        positiveFeedbackCount: 1,
        negativeFeedbackCount: 0,
        status: 'NORMAL',
      },
      {
        // Deleted article category
        categoryId: 'c2',
        userId: 'an-user',
        appId: 'WEBSITE',
        status: 'DELETED',
        positiveFeedbackCount: 1,
        negativeFeedbackCount: 0,
        createdAt: '2021-01-01T00:00:00.000Z',
      },
      {
        // Normal article category
        categoryId: 'c3',
        userId: 'some-user',
        appId: 'WEBSITE',
        status: 'NORMAL',
        positiveFeedbackCount: 1,
        negativeFeedbackCount: 0,
        createdAt: '2021-01-01T00:00:00.000Z',
      },
    ],
  },
  '/articlecategoryfeedbacks/doc/f1': {
    articleId: 'a2',
    categoryId: 'c1',
  },
  '/categories/doc/c1': {
    title: 'Category 1',
    description: 'Description for category 1',
  },
  '/categories/doc/c2': {
    title: 'Category 2',
    description: 'Description for category 2',
  },
  '/categories/doc/c3': {
    title: 'Category 3',
    description: 'Description for category 3',
  },
};
